CREATE TABLE person (handle VARCHAR(50) PRIMARY KEY NOT NULL, given_name TEXT, surname TEXT, blob_data BLOB))
CREATE TABLE family (handle VARCHAR(50) PRIMARY KEY NOT NULL, blob_data BLOB)
CREATE TABLE source (handle VARCHAR(50) PRIMARY KEY NOT NULL, blob_data BLOB)
CREATE TABLE citation (handle VARCHAR(50) PRIMARY KEY NOT NULL, blob_data BLOB)
CREATE TABLE event (handle VARCHAR(50) PRIMARY KEY NOT NULL, blob_data BLOB)
CREATE TABLE media (handle VARCHAR(50) PRIMARY KEY NOT NULL, blob_data BLOB)
CREATE TABLE place (handle VARCHAR(50) PRIMARY KEY NOT NULL, enclosed_by VARCHAR(50), blob_data BLOB)
CREATE TABLE repository (handle VARCHAR(50) PRIMARY KEY NOT NULL, blob_data BLOB)
CREATE TABLE note (handle VARCHAR(50) PRIMARY KEY NOT NULL, blob_data BLOB)
CREATE TABLE tag (handle VARCHAR(50) PRIMARY KEY NOT NULL, blob_data BLOB)
CREATE TABLE reference (obj_handle VARCHAR(50), obj_class TEXT, ref_handle VARCHAR(50), ref_class TEXT)
CREATE TABLE name_group (name VARCHAR(50) PRIMARY KEY NOT NULL, grouping TEXT)
CREATE TABLE metadata (setting VARCHAR(50) PRIMARY KEY NOT NULL, value BLOB)
CREATE TABLE gender_stats (given_name TEXT, female INTEGER, male INTEGER, unknown INTEGER)
CREATE INDEX person_gramps_id ON person(gramps_id)
CREATE INDEX person_surname ON person(surname)
CREATE INDEX person_given_name ON person(given_name)
CREATE INDEX source_title ON source(title)
CREATE INDEX source_gramps_id ON source(gramps_id)
CREATE INDEX citation_page ON citation(page)
CREATE INDEX citation_gramps_id ON citation(gramps_id)
CREATE INDEX media_desc ON media(desc)
CREATE INDEX media_gramps_id ON media(gramps_id)
CREATE INDEX place_title ON place(title)
CREATE INDEX place_enclosed_by ON place(enclosed_by)
CREATE INDEX place_gramps_id ON place(gramps_id)
CREATE INDEX tag_name ON tag(name)
CREATE INDEX reference_ref_handle ON reference(ref_handle)
CREATE INDEX family_gramps_id ON family(gramps_id)
CREATE INDEX event_gramps_id ON event(gramps_id)
CREATE INDEX repository_gramps_id ON repository(gramps_id)
CREATE INDEX note_gramps_id ON note(gramps_id)
CREATE INDEX reference_obj_handle ON reference(obj_handle)
